# -*- coding: utf-8 -*-
"""Soal1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fO8RYmsAXxqTodLviTFTaKU-kY45TpNK
"""

# Sistem pakar sederhana untuk mendeteksi hama tanaman

def deteksi_hama(gejala):
    hasil = []
    if "daun menguning" in gejala:
        hasil.append("Kutu Putih")
    if "bercak hitam" in gejala:
        hasil.append("Jamur Daun")
    if "daun berlubang" in gejala:
        hasil.append("Ulat Daun")
    if "tanaman layu" in gejala:
        hasil.append("Serangan Nematoda")
    return hasil

# Contoh input
gejala_input = ["daun menguning", "bercak hitam"]

# Proses inferensi
hasil_hama = deteksi_hama(gejala_input)

# Output
print("Berdasarkan gejala, kemungkinan hama yang menyerang adalah:")
for hama in hasil_hama:
    print(f"- {hama}")